# Generated by Django 5.1 on 2024-08-28 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='avatar/')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('MB', 'MITHU'), ('NB', 'NIRANJAN'), ('KB', 'KHUKHU'), ('AB', 'ANURAG')], default='', max_length=10)),
            ],
        ),
    ]
