# Generated by Django 5.1 on 2024-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameslist',
            name='type',
            field=models.CharField(choices=[('MB', 'MITHU'), ('NB', 'NIRANJAN'), ('KB', 'KHUKHU'), ('AB', 'ANURAG')], default='MB', max_length=9),
        ),
    ]
